### ISSUE TITLE
Fail to start server built using Maven Overlay Project

### ISSUE THREAD

**Issue by lhwong** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1130]
Hi,

I cloned the mitreid-connect/example-openid-connect-overlay project and made change to the properties/version in example-openid-connect-overlay/pom.xml. 

```

  <properties>
    <mitreid-version>1.3.0-SNAPSHOT</mitreid-version>
    <java-version>1.8</java-version>
  </properties>


```

I got the following error upon starting up. Also, get the same error if no change made to the pom.xml. 

```
11-Oct-2016 17:10:50.006 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server version:        Apache Tomcat/8.0.28
11-Oct-2016 17:10:50.008 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server built:          Oct 7 2015 18:25:21 UTC
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Server number:         8.0.28.0
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Name:               Windows 10
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log OS Version:            10.0
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Architecture:          amd64
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Java Home:             C:\Java\jdk1.8.0_73\jre
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Version:           1.8.0_73-b02
11-Oct-2016 17:10:50.009 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log JVM Vendor:            Oracle Corporation
11-Oct-2016 17:10:50.010 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_BASE:         C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28
11-Oct-2016 17:10:50.010 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log CATALINA_HOME:         C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28
11-Oct-2016 17:10:50.010 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.config.file=C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\conf\logging.properties
11-Oct-2016 17:10:50.010 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.util.logging.manager=org.apache.juli.ClassLoaderLogManager
11-Oct-2016 17:10:50.011 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.endorsed.dirs=C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\endorsed
11-Oct-2016 17:10:50.013 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.base=C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28
11-Oct-2016 17:10:50.013 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Dcatalina.home=C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28
11-Oct-2016 17:10:50.014 INFO [main] org.apache.catalina.startup.VersionLoggerListener.log Command line argument: -Djava.io.tmpdir=C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\temp
11-Oct-2016 17:10:50.015 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent Loaded APR based Apache Tomcat Native library 1.1.33 using APR version 1.5.1.
11-Oct-2016 17:10:50.016 INFO [main] org.apache.catalina.core.AprLifecycleListener.lifecycleEvent APR capabilities: IPv6 [true], sendfile [true], accept filters [false], random [true].
11-Oct-2016 17:10:51.097 INFO [main] org.apache.catalina.core.AprLifecycleListener.initializeSSL OpenSSL successfully initialized (OpenSSL 1.0.1m 19 Mar 2015)
11-Oct-2016 17:10:51.258 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["http-apr-8080"]
11-Oct-2016 17:10:51.270 INFO [main] org.apache.coyote.AbstractProtocol.init Initializing ProtocolHandler ["ajp-apr-8009"]
11-Oct-2016 17:10:51.272 INFO [main] org.apache.catalina.startup.Catalina.load Initialization processed in 1698 ms
11-Oct-2016 17:10:51.320 INFO [main] org.apache.catalina.core.StandardService.startInternal Starting service Catalina
11-Oct-2016 17:10:51.320 INFO [main] org.apache.catalina.core.StandardEngine.startInternal Starting Servlet Engine: Apache Tomcat/8.0.28
                                                                                                        11-Oct-2016 17:10:51.390 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deploying web application archive C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\my-openid-connect-server.war
11-Oct-2016 17:10:52.582 INFO [localhost-startStop-1] org.apache.jasper.servlet.TldScanner.scanJars At least one JAR was scanned for TLDs yet contained no TLDs. Enable debug logging for this logger for a complete list of JARs that were scanned but no TLDs were found in them. Skipping unneeded JARs during scanning can improve startup time and JSP compilation time.
INFO : org.springframework.web.context.ContextLoader - Root WebApplicationContext: initialization started
INFO : org.springframework.web.context.support.XmlWebApplicationContext - Refreshing Root WebApplicationContext: startup date [Tue Oct 11 17:10:53 SGT 2016]; root of context hierarchy
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/application-context.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/server-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from URL [file:/etc/mitreid-connect/server-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/data-context.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from URL [file:/etc/mitreid-connect/data-context.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/authz-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/locale-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/user-context.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/assertion-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/jpa-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/crypto-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/task-config.xml]
INFO : org.springframework.beans.factory.xml.XmlBeanDefinitionReader - Loading XML bean definitions from ServletContext resource [/WEB-INF/local-config.xml]
INFO : org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'taskExecutor' of type [class org.springframework.scheduling.config.TaskExecutorFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
INFO : org.springframework.context.support.PostProcessorRegistrationDelegate$BeanPostProcessorChecker - Bean 'taskExecutor' of type [class org.springframework.scheduling.concurrent.ThreadPoolTaskExecutor] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying)
WARN : org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.annotation.internalAsyncAnnotationProcessor': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.aop.interceptor.AsyncExecutionInterceptor.<init>(Ljava/util/concurrent/Executor;Lorg/springframework/aop/interceptor/AsyncUncaughtExceptionHandler;)V
ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'org.springframework.context.annotation.internalAsyncAnnotationProcessor': Initialization of bean failed; nested exception is java.lang.NoSuchMethodError: org.springframework.aop.interceptor.AsyncExecutionInterceptor.<init>(Ljava/util/concurrent/Executor;Lorg/springframework/aop/interceptor/AsyncUncaughtExceptionHandler;)V
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:547)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:476)
        at org.springframework.beans.factory.support.AbstractBeanFactory$1.getObject(AbstractBeanFactory.java:303)
        at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:230)
        at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:299)
        at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:199)
        at org.springframework.context.support.PostProcessorRegistrationDelegate.registerBeanPostProcessors(PostProcessorRegistrationDelegate.java:220)
        at org.springframework.context.support.AbstractApplicationContext.registerBeanPostProcessors(AbstractApplicationContext.java:619)
        at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:465)
        at org.springframework.web.context.ContextLoader.configureAndRefreshWebApplicationContext(ContextLoader.java:434)
        at org.springframework.web.context.ContextLoader.initWebApplicationContext(ContextLoader.java:306)
        at org.springframework.web.context.ContextLoaderListener.contextInitialized(ContextLoaderListener.java:106)
        at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4738)
        at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5181)
        at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150)
        at org.apache.catalina.core.ContainerBase.addChildInternal(ContainerBase.java:725)
        at org.apache.catalina.core.ContainerBase.addChild(ContainerBase.java:701)
        at org.apache.catalina.core.StandardHost.addChild(StandardHost.java:717)
        at org.apache.catalina.startup.HostConfig.deployWAR(HostConfig.java:945)
        at org.apache.catalina.startup.HostConfig$DeployWar.run(HostConfig.java:1798)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoSuchMethodError: org.springframework.aop.interceptor.AsyncExecutionInterceptor.<init>(Ljava/util/concurrent/Executor;Lorg/springframework/aop/interceptor/AsyncUncaughtExceptionHandler;)V
        at org.springframework.scheduling.annotation.AnnotationAsyncExecutionInterceptor.<init>(AnnotationAsyncExecutionInterceptor.java:60)
        at org.springframework.scheduling.annotation.AsyncAnnotationAdvisor.buildAdvice(AsyncAnnotationAdvisor.java:150)
        at org.springframework.scheduling.annotation.AsyncAnnotationAdvisor.<init>(AsyncAnnotationAdvisor.java:99)
        at org.springframework.scheduling.annotation.AsyncAnnotationBeanPostProcessor.setBeanFactory(AsyncAnnotationBeanPostProcessor.java:105)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeAwareMethods(AbstractAutowireCapableBeanFactory.java:1591)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1559)
        at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:539)
        ... 24 more
11-Oct-2016 17:10:55.884 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal One or more listeners failed to start. Full details will be found in the appropriate container log file
11-Oct-2016 17:10:55.895 SEVERE [localhost-startStop-1] org.apache.catalina.core.StandardContext.startInternal Context [/my-openid-connect-server] startup failed due to previous errors
11-Oct-2016 17:10:55.917 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployWAR Deployment of web application archive C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\my-openid-connect-server.war has finished in 4,526 ms
11-Oct-2016 17:10:55.918 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\docs
11-Oct-2016 17:10:56.080 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\docs has finished in 162 ms
11-Oct-2016 17:10:56.080 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\examples
11-Oct-2016 17:10:56.593 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\examples has finished in 513 ms
11-Oct-2016 17:10:56.594 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\host-manager
11-Oct-2016 17:10:56.743 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\host-manager has finished in 149 ms
11-Oct-2016 17:10:56.749 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\manager
11-Oct-2016 17:10:56.948 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\manager has finished in 200 ms
11-Oct-2016 17:10:56.949 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deploying web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\ROOT
11-Oct-2016 17:10:57.099 INFO [localhost-startStop-1] org.apache.catalina.startup.HostConfig.deployDirectory Deployment of web application directory C:\Users\User\Desktop\infinode\apache-tomcat-8.0.28-windows-x64\apache-tomcat-8.0.28\webapps\ROOT has finished in 150 ms
11-Oct-2016 17:10:57.109 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["http-apr-8080"]
11-Oct-2016 17:10:57.120 INFO [main] org.apache.coyote.AbstractProtocol.start Starting ProtocolHandler ["ajp-apr-8009"]
11-Oct-2016 17:10:57.121 INFO [main] org.apache.catalina.startup.Catalina.start Server startup in 5848 ms

```

**Comment by ericspreher** [comment]
I also had  the same error when attempting a maven build with 1.2.6. There some conflict with the spring-aop artifact. I was able to resolve it adding an exclusion in pom file like below:

      <dependency>
      	<groupId>org.mitre</groupId>
       	<artifactId>openid-connect-common</artifactId>
       	<version>${mitreid-version}</version>
       	<exclusions>
       		<exclusion>
       			<groupId>org.springframework</groupId>
       			<artifactId>spring-aop</artifactId>
       		</exclusion>
       	</exclusions>
      </dependency>

**Comment by jricher** [comment]
The example overlay project hasn't been updated to 1.3 yet, but it should be working on 1.2.6 so we'll look into that change. You should not have to exclude spring artifacts from your overlay like this, as that would mean that your overlay configuration is pulling in a different spring version from the underlying project, which won't work. More likely there are a couple of version variables out of date in the example overlay code that need to be updated for 1.2.6.

**Comment by jricher** [comment]
I've been looking into this and it seems that the right answer is to move the dependencies around a bit. I've got this working in a local overlay and we'll push this change into the example project:

```
	<dependencyManagement>
		<dependencies>
			<dependency>
				<groupId>org.mitre</groupId>
				<artifactId>openid-connect-parent</artifactId>
				<type>pom</type>
				<version>${mitreid-version}</version>
				<scope>import</scope>
			</dependency>
		</dependencies>
	</dependencyManagement>

	<dependencies>
		<dependency>
			<groupId>org.mitre</groupId>
			<artifactId>openid-connect-server-webapp</artifactId>
			<type>war</type>
		</dependency>
	</dependencies>
```

**Comment by ericspreher** [comment]
After making these changes to my pom, the dependencies are working setup properly and building as expected. Thanks for your help.
