### ISSUE TITLE
uma-server-webapp startup issues

### ISSUE THREAD

**Issue by kushal256** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1139]
When I checkout from master, I do the following:

> cd OpenID-Connect-Java-Spring-Server/uma-server-webapp
> mvn jetty:run

I see these exceptions:
WARN : org.springframework.web.context.support.XmlWebApplicationContext - Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAssertionTokenGranter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mitre.jwt.assertion.AssertionValidator org.mitre.oauth2.token.JWTAssertionTokenGranter.validator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}
ERROR: org.springframework.web.context.ContextLoader - Context initialization failed
org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'jwtAssertionTokenGranter': Injection of autowired dependencies failed; nested exception is org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mitre.jwt.assertion.AssertionValidator org.mitre.oauth2.token.JWTAssertionTokenGranter.validator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}
Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mitre.jwt.assertion.AssertionValidator org.mitre.oauth2.token.JWTAssertionTokenGranter.validator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
    at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
    at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
    ... 65 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}

The jetty server still starts, but I cannot access http://localhost:8080/uma-server-webapp/.well-known/uma-configuration (not sure if this is the correct URL, please correct me if I'm wrong).

**Comment by jricher** [comment]
Are you building the project from the root? 

Also, the UMA server uses an overlay, and I'm not sure that Jetty support has been tested very well on it. Our team's usual development and deployment use Tomcat.

**Comment by kushal256** [comment]
Yes, building from the root.

Just tried with tomcat 7.0.70, and getting the same error in my logs/catalina.out file (see below if interested).

Interestingly enough, this exception is related to Spring autowiring for org.mitre.oauth2.token.JWTAssertionTokenGranter::validator field.  This class lives in openid-connect-server-1.3.0-SNAPSHOT.jar, and I do NOT get this exception when running the openid-connect-server-webapp webapp.  I can start that webapp fine and access it's various endpoints just fine.

Is there something specific with uma-server-webapp that would affect this given field?

-------------
from logs/catalina.out:

Caused by: org.springframework.beans.factory.BeanCreationException: Could not autowire field: private org.mitre.jwt.assertion.AssertionValidator org.mitre.oauth2.token.JWTAssertionTokenGranter.validator; nested exception is org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:561)
        at org.springframework.beans.factory.annotation.InjectionMetadata.inject(InjectionMetadata.java:88)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor.postProcessPropertyValues(AutowiredAnnotationBeanPostProcessor.java:331)
        ... 26 more
Caused by: org.springframework.beans.factory.NoSuchBeanDefinitionException: No qualifying bean of type [org.mitre.jwt.assertion.AssertionValidator] found for dependency: expected at least 1 bean which qualifies as autowire candidate for this dependency. Dependency annotations: {@org.springframework.beans.factory.annotation.Autowired(required=true), @org.springframework.beans.factory.annotation.Qualifier(value=jwtAssertionValidator)}
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.raiseNoSuchBeanDefinitionException(DefaultListableBeanFactory.java:1301)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.doResolveDependency(DefaultListableBeanFactory.java:1047)
        at org.springframework.beans.factory.support.DefaultListableBeanFactory.resolveDependency(DefaultListableBeanFactory.java:942)
        at org.springframework.beans.factory.annotation.AutowiredAnnotationBeanPostProcessor$AutowiredFieldElement.inject(AutowiredAnnotationBeanPostProcessor.java:533)
        ... 28 more
Oct 28, 2016 2:58:15 PM org.apache.catalina.core.StandardContext startInternal
SEVERE: One or more listeners failed to start. Full details will be found in the appropriate container log file
Oct 28, 2016 2:58:15 PM org.apache.catalina.core.StandardContext startInternal
**SEVERE: Context [/uma-server-webapp] startup failed due to previous errors**
Oct 28, 2016 2:58:15 PM org.apache.catalina.loader.WebappClassLoaderBase clearReferencesJdbc
SEVERE: The web application [/uma-server-webapp] registered the JDBC driver [org.hsqldb.jdbc.JDBCDriver] but failed to unregister it when the web application was stopped. To prevent a memory leak, the JDBC Driver has been forcibly unregistered.
Oct 28, 2016 2:58:15 PM org.apache.catalina.startup.HostConfig deployWAR
INFO: Deployment of web application archive ~/tomcat/webapps/uma-server-webapp.war has finished in 2,661 ms

**Comment by jricher** [comment]
OK, I think that's interesting. The assertion validator stuff is new in 1.3 and it's entirely possible (likely?) that there's a configuration change between the core OIDC server and the UMA server due to that. The UMA server still isn't a clean overlay on top of the OIDC server, so sometimes things get out of sync. One of the goals in 1.3 is to make this relationship cleaner so that things like this don't happen.

**Comment by sschu** [comment]
As far as I can see, the reason is application-context.xml of openid-connect-server-webapp being overlayed by uma-server-webapp. The overlayed version does not include assertion-config.xml defining the missing bean. Adding that include to application-context.xml solves the startup problem. Still not sure this is a good solution as https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/wiki/Maven-Overlay-Project-How-To suggests not overlaying application-context.xml at all.

**Comment by jricher** [comment]
Right, that's exactly what I meant when I said that the UMA server isn't a clean overlay on the base project yet. :)

**Comment by sschu** [comment]
Are there any specific plans for this or is there anything I could do? :)

**Comment by sschu** [comment]
I opened a pull request for this: https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/1174 It is essentially just a quick fix. Problems like this will most likely reappear due to overlays being a very coarse-grained kind of inheritance with not static type checking to detect problems. This means a lot of test would be necessary, especially for the Javascript part that also gets overlayed partially. However, I don't have a better solution right now.

**Comment by kushal256** [comment]
@sschu Your fix looks good for my simple test of connecting to http://localhost:8080/uma-server-webapp/.well-known/uma-configuration

I'll close this ticket now, if any other issues come up, will raise in a new ticket.

Thanks!!
