### ISSUE TITLE
User Info problem

### ISSUE THREAD

**Issue by Faury** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1144]
Hello,

I have a problem related to /userinfo, actually, the absence of it.

I also had the problem that I didn't have the /jwk in my server, but I solved this creating my own endpoint that returned the jwk string.

What I did, I simply removed the userinfo uri from the org.mitre.openid.connect.config.ServerConfiguration, and in the end I got this error (I replaced the sub and iss values by ##### just for my security reasons) :

_Application Error
SRVE0777E: Exceção lançada pela classe de aplicativo 'com.google.common.cache.LocalCache$Segment.getAndRecordStats:2350'
com.google.common.cache.CacheLoader$InvalidCacheLoadException: CacheLoader returned null for key org.mitre.openid.connect.model.PendingOIDCAuthenticationToken@69799102: Principal: {sub=########, iss=########}; Credentials: [PROTECTED]; Authenticated: false; Details: null; Not granted any authorities.
at com.google.common.cache.LocalCache$Segment.getAndRecordStats(LocalCache.java:2350)
at com.google.common.cache.LocalCache$Segment.loadSync(LocalCache.java:2320)
at com.google.common.cache.LocalCache$Segment.lockedGetOrLoad(LocalCache.java:2282)
at com.google.common.cache.LocalCache$Segment.get(LocalCache.java:2197)
at com.google.common.cache.LocalCache.get(LocalCache.java:3937)
at com.google.common.cache.LocalCache.getOrLoad(LocalCache.java:3941)
at com.google.common.cache.LocalCache$LocalLoadingCache.get(LocalCache.java:4824)
at org.mitre.openid.connect.client.UserInfoFetcher.loadUserInfo(UserInfoFetcher.java:72)
at org.mitre.openid.connect.client.OIDCAuthenticationProvider.authenticate(OIDCAuthenticationProvider.java:68)
at org.springframework.security.authentication.ProviderManager.authenticate(ProviderManager.java:167)
at org.mitre.openid.connect.client.OIDCAuthenticationFilter.handleAuthorizationCodeResponse(OIDCAuthenticationFilter.java:590)
at org.mitre.openid.connect.client.OIDCAuthenticationFilter.attemptAuthentication(OIDCAuthenticationFilter.java:184)
at org.springframework.security.web.authentication.AbstractAuthenticationProcessingFilter.doFilter(AbstractAuthenticationProcessingFilter.java:217)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.authentication.logout.LogoutFilter.doFilter(LogoutFilter.java:120)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.csrf.CsrfFilter.doFilterInternal(CsrfFilter.java:96)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.header.HeaderWriterFilter.doFilterInternal(HeaderWriterFilter.java:64)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.context.request.async.WebAsyncManagerIntegrationFilter.doFilterInternal(WebAsyncManagerIntegrationFilter.java:53)
at org.springframework.web.filter.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:107)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.context.SecurityContextPersistenceFilter.doFilter(SecurityContextPersistenceFilter.java:91)
at org.springframework.security.web.FilterChainProxy$VirtualFilterChain.doFilter(FilterChainProxy.java:330)
at org.springframework.security.web.FilterChainProxy.doFilterInternal(FilterChainProxy.java:213)
at org.springframework.security.web.FilterChainProxy.doFilter(FilterChainProxy.java:176)
at org.springframework.web.filter.DelegatingFilterProxy.invokeDelegate(DelegatingFilterProxy.java:344)
at org.springframework.web.filter.DelegatingFilterProxy.doFilter(DelegatingFilterProxy.java:261)
at com.ibm.ws.webcontainer.filter.FilterInstanceWrapper.doFilter(FilterInstanceWrapper.java:206)
at [internal classes]_

Someone has any idea what can be causing the error?

This is shown in the browser, in the log it doesn't appear, but I can notice that it didn't save the security context:

_2016-11-04 12:10:26,821 DEBUG (org.springframework.security.authentication.ProviderManager:162) - Authentication attempt using org.mitre.openid.connect.client.OIDCAuthenticationProvider
2016-11-04 12:10:26,821  WARN (org.mitre.openid.connect.client.UserInfoFetcher:97) - No userinfo endpoint, not fetching.
2016-11-04 12:10:26,822 DEBUG (org.springframework.security.web.context.HttpSessionSecurityContextRepository:337) - SecurityContext is empty or contents are anonymous - context will not be stored in HttpSession.
2016-11-04 12:10:26,822 DEBUG (org.springframework.security.web.context.SecurityContextPersistenceFilter:105) - SecurityContextHolder now cleared, as request processing completed_

Glad if someone can help me with some hint.

**Comment by Faury** [comment]
I discovered that this is a bug related to the cache of the UserInfo.

When you don't have /userinfo the UserInfoFetcher still tries to take value from the cache, but the cache is empty since it was never filled.

So I regressed some versions until the point where this cache was not implemented and voilá, it worked with the version 1.2.2.

I just will let the issue open since I believe it's a bug and need to be fixed in the future versions.
