### ISSUE TITLE
Getting "Interface can't be instantiated!" when saving client with authority.

### ISSUE THREAD

**Issue by tsolakp** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1279]
Getting the following error: 

"Interface can't be instantiated! Interface name: org.springframework.security.core.GrantedAuthority" 

after populating "client_authority" table with one sample authority, restarting the app and trying to update client in the UI.

To solve it I had to add the following to ClientAPI class:

```
            .registerTypeAdapter(GrantedAuthority.class, new JsonDeserializer<GrantedAuthority>() {
                @Override
                public GrantedAuthority deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {                  
                    JsonObject jsonObject =  json.getAsJsonObject(); 
                    SimpleGrantedAuthority result = context.deserialize( jsonObject, SimpleGrantedAuthority.class );
                    return result;                   
                }
            })	
```

Here is the stack trace:

```
java.lang.UnsupportedOperationException: Interface can't be instantiated! Interface name: org.springframework.security.core.GrantedAuthority
	at com.google.gson.internal.UnsafeAllocator.assertInstantiable(UnsafeAllocator.java:117)
	at com.google.gson.internal.UnsafeAllocator.access$000(UnsafeAllocator.java:31)
	at com.google.gson.internal.UnsafeAllocator$1.newInstance(UnsafeAllocator.java:49)
	at com.google.gson.internal.ConstructorConstructor$14.construct(ConstructorConstructor.java:223)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:210)
	at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:129)
	at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:220)
	at com.google.gson.Gson.fromJson(Gson.java:887)
	at com.google.gson.Gson.fromJson(Gson.java:952)
	at com.google.gson.Gson.fromJson(Gson.java:925)
	at org.mitre.openid.connect.web.ClientAPI.apiUpdateClient(ClientAPI.java:368)
	at org.mitre.openid.connect.web.ClientAPI$$FastClassBySpringCGLIB$$6a338d95.invoke(<generated>)
	at org.springframework.cglib.proxy.MethodProxy.invoke(MethodProxy.java:204)
	at org.springframework.aop.framework.CglibAopProxy$CglibMethodInvocation.invokeJoinpoint(CglibAopProxy.java:721)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:157)
	at org.springframework.security.access.intercept.aopalliance.MethodSecurityInterceptor.invoke(MethodSecurityInterceptor.java:69)
	at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:179)
	at org.springframework.aop.framework.CglibAopProxy$DynamicAdvisedInterceptor.intercept(CglibAopProxy.java:656)
	at org.mitre.openid.connect.web.ClientAPI$$EnhancerBySpringCGLIB$$d7c8ff37.apiUpdateClient(<generated>)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.web.method.support.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:205)
	at org.springframework.web.method.support.InvocableHandlerMethod.invokeForRequest(InvocableHandlerMethod.java:133)
	at org.springframework.web.servlet.mvc.method.annotation.ServletInvocableHandlerMethod.invokeAndHandle(ServletInvocableHandlerMethod.java:116)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.invokeHandlerMethod(RequestMappingHandlerAdapter.java:827)
	at org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerAdapter.handleInternal(RequestMappingHandlerAdapter.java:738)
	at org.springframework.web.servlet.mvc.method.AbstractHandlerMethodAdapter.handle(AbstractHandlerMethodAdapter.java:85)
	at org.springframework.web.servlet.DispatcherServlet.doDispatch(DispatcherServlet.java:963)
	at org.springframework.web.servlet.DispatcherServlet.doService(DispatcherServlet.java:897)
	at org.springframework.web.servlet.FrameworkServlet.processRequest(FrameworkServlet.java:970)
	at org.springframework.web.servlet.FrameworkServlet.doPut(FrameworkServlet.java:883)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:651)
```

**Comment by jricher** [comment]
Clients with specific authorities are largely untested and unused in the current version of the app. What's your use case for instantiating this?

**Comment by tsolakp** [comment]
I needed this in order to pass client "authority" to JWT claim in ConnectTokenEnhancer in order to be able to authorize against my Spring Boot resource (Spring maps authority claim to role).
Here is the code snippet in ConnectTokenEnhancer:

```
.claim( "authorities", client.getAuthorities() != null ? 
				client.getAuthorities().stream().map( a -> a.getAuthority() ).collect( Collectors.toList() ) : Collections.emptyList() );
```
