### ISSUE TITLE
UT000010: Session not found HHRaL1VUp0KovHkXRXaJtGJnTRvQYwwdcjGDIAkg

### ISSUE THREAD

**Issue by alexbrigido** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1434]
Hi everyone!

   I'm getting this error on EAP 7.0.5.GA sometimes.
   I got a F5 balancer and 2 nodes with EAP 7.0.5.GA. 

Stacktrace:
`2018-11-01 06:50:15,037 ERROR [io.undertow.request] (default task-3) UT005023: Exception handling request to /devicecode: java.lang.IllegalStateException: UT000010: Session not found HHRaL1VUp0KovHkXRXaJtGJnTRvQYwwdcjGDIAkg
at io.undertow.server.session.InMemorySessionManager$SessionImpl.getAttribute(InMemorySessionManager.java:472)
at io.undertow.servlet.spec.HttpSessionImpl.getAttribute(HttpSessionImpl.java:122)
at org.jboss.weld.context.http.HttpSessionContextImpl.checkBeanIdentifierIndexConsistency(HttpSessionContextImpl.java:98)
at org.jboss.weld.context.http.HttpSessionContextImpl.associate(HttpSessionContextImpl.java:47)
at org.jboss.weld.context.http.HttpSessionContextImpl.associate(HttpSessionContextImpl.java:23)
at org.jboss.weld.servlet.HttpContextLifecycle.requestInitialized(HttpContextLifecycle.java:237)
at org.jboss.weld.servlet.WeldInitialListener.requestInitialized(WeldInitialListener.java:152)
at io.undertow.servlet.core.ApplicationListeners.requestInitialized(ApplicationListeners.java:245)
at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:284)
at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:264)
at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:175)
at io.undertow.server.Connectors.executeRootHandler(Connectors.java:209)
at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:802)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
at java.lang.Thread.run(Thread.java:748)`

`2018-11-01 06:50:15,038 WARN  [org.jboss.weld.Servlet] (default task-3) WELD-000717: Unable to deactivate context org.jboss.weld.context.http.HttpSessionContextImpl@6c98506e when destroying request HttpServletRequestImpl [ POST /devicecode ]`

This is all stacktrace and occurs 3000 times. The session id HHRaL1VUp0KovHkXRXaJtGJnTRvQYwwdcjGDIAkg is always the same.
The issue is intermittent and occurs sometimes.

undertow version is 1.3.21.Final-redhat-1

Anyone has ideia?

**Comment by srmoore** [comment]
I don't really know EAP that much but it seems like the session replication/sticky sessions isn't set up right for your load balancing setup. I did find one article that said that EAP 7 had issues with session replication unless they are running on the same machine with different ports. I didn't dig into that, and don't know if they have updated that particular issue.

**Comment by alexbrigido** [comment]
Thanks for your support. I do not know if JBoss is the problem. I just think a little bit strange that the AuthorizationRequestFilter filter always creates a Session for any request, instead just creating it at "/ authorize" request.

            public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {

		HttpServletRequest request = (HttpServletRequest) req;
		HttpServletResponse response = (HttpServletResponse) res;
		HttpSession session = request.getSession();

		// skip everything that's not an authorize URL
		if (!requestMatcher.matches(request)) {
			chain.doFilter(req, res);
			return;
		}

**Comment by srmoore** [comment]
That's because `HttpServletRequest`'s `getSession()` "Returns the current session associated with this request, or if the request does not have a session, creates one."  (from the Javadoc.) So it isn't actually making a new one every time.

**Comment by alexbrigido** [comment]
To don't create one, the code should be:

        public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {

	  // skip everything that's not an authorize URL
	    if (!requestMatcher.matches((HttpServletRequest) req)) {
		chain.doFilter(req, res);
		return;
	     }

	   HttpServletRequest request = (HttpServletRequest) req;
	   HttpServletResponse response = (HttpServletResponse) res;
	  HttpSession session = request.getSession();

Don't you think?
**"if the request does not have a session, creates one"**

**Comment by alexbrigido** [comment]
My scenario has multiple requests from hundreds of different users.

**Comment by srmoore** [comment]
I see you are posting to the `/devicecode` endpoint, and yes, that doesn't need a session associated with it, but it really shouldn't matter. The next step in the process is the user approving the device, which will require a session. So, if you don't make a session for the `POST` to the device code endpoint, you just hit this issue when a user tries to log in to approve the device.

The error is indicating that the server is getting a session ID that doesn't exist on the server, which leads me to believe the load balancer is sending a session ID when it shouldn't be, or to the wrong server. My next debugging step would be to see if you can talk to one of the OIDC servers directly rather than via the load balancer and see if that works. Narrow down where the real issue is.

**Comment by alexbrigido** [comment]
Ok @srmoore, thank you so much! I'll investigate the error in more detail.

**Comment by thomasmey** [comment]
> Thanks for your support. I do not know if JBoss is the problem. I just think a little bit strange that the AuthorizationRequestFilter filter always creates a Session for any request, instead just creating it at "/ authorize" request.
> 
> ```
>         public void doFilter(ServletRequest req, ServletResponse res, FilterChain chain) throws IOException, ServletException {
> 
> 	HttpServletRequest request = (HttpServletRequest) req;
> 	HttpServletResponse response = (HttpServletResponse) res;
> 	HttpSession session = request.getSession();
> 
> 	// skip everything that's not an authorize URL
> 	if (!requestMatcher.matches(request)) {
> 		chain.doFilter(req, res);
> 		return;
> 	}
> ```

Yes, I also noticed this bug today.

The filter shouldn't create a session at this place.
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/blob/a2e8cb1a67a5546fdef11c604142a847e7c61261/openid-connect-server/src/main/java/org/mitre/openid/connect/filter/AuthorizationRequestFilter.java#L108

**Comment by thomasmey** [comment]
Also some jsp pages like error also creates new http sessions. I guess some jsp pages misses a page attribute to not create sessions.

**Comment by olye0216** [comment]
@alexbrigido Hi!
Have succeeded in attempts to solve this problem? If yes, how you've solved it? :)
