### ISSUE TITLE
com.nimbusds.oauth2.sdk.ParseException: Unexpected HTTP status code, must be 302 (Found): 200 

### ISSUE THREAD

**Issue by hkandika** [mitreid-connect/OpenID-Connect-Java-Spring-Server#1508]
While sending authentication request to openid-connect-server-webapp I'm getting below error while parsing httpResponse

com.nimbusds.oauth2.sdk.ParseException: Unexpected HTTP status code, must be 302 (Found): 200
	at com.nimbusds.openid.connect.sdk.AuthenticationResponseParser.parse(AuthenticationResponseParser.java:124)
	at com.example.server.sso.oidc.Servlets$LoginServlet.authenticate(Servlets.java:164)
	at com.example.server.sso.oidc.Servlets$LoginServlet.doGet(Servlets.java:67)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:748)

here is my code 
			State state = new State();
			Nonce nonce = new Nonce();
			Scope scope = Scope.parse("openid");
			ClientID clientID = new ClientID(clientid_cd.getPropvalue());
			URI redirectURI = new URI("https://" + req.getServerName() + Utils.Constants.OIDC_CLIENT_REDIRECT_URI_ENDPOINT);
			
			// Compose the request
			AuthenticationRequest authenticationRequest = new AuthenticationRequest(
			  providerMetadata.getAuthorizationEndpointURI(),
			  new ResponseType(ResponseType.Value.CODE),
			  scope, 
			  clientID, 
			  redirectURI, 
			  state, 
			  nonce);
			
			//send authentication request to openid provider and receive response
			HTTPResponse httpResponse = authenticationRequest.toHTTPRequest().send();

Error is coming at below line.
			AuthenticationResponse authenticationResponse = AuthenticationResponseParser.parse(httpResponse);

Please help

**Comment by hkandika** [comment]
I'm past above issue I found there are multiple versions of oauth sdk jar file in my classpath, looks like it was picking old one.

But now I'm getting following exception
javax.net.ssl.SSLHandshakeException: sun.security.validator.ValidatorException: PKIX path building failed: sun.security.provider.certpath.SunCertPathBuilderException: unable to find valid certification path to requested target
	at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1950)
	at sun.net.www.protocol.http.HttpURLConnection$10.run(HttpURLConnection.java:1945)
	at java.security.AccessController.doPrivileged(Native Method)
	at sun.net.www.protocol.http.HttpURLConnection.getChainedException(HttpURLConnection.java:1944)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1514)
	at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1498)
	at java.net.HttpURLConnection.getResponseCode(HttpURLConnection.java:480)
	at sun.net.www.protocol.https.HttpsURLConnectionImpl.getResponseCode(HttpsURLConnectionImpl.java:352)
	at com.nimbusds.oauth2.sdk.http.HTTPRequest.send(HTTPRequest.java:901)



at this line of code
//send authentication request to openid provider and receive response			
HTTPResponse httpResponse = authenticationRequest.toHTTPRequest().send();

I have myweb aplication deployed in server_1
and openid-connect-server-webapp.war deployed in server_2

I created a servlet in server_1 and sending an authentication request to server_2

I appreciate any help. Thank you.

**Comment by hkandika** [comment]
I'm able to resolve it by downloading openid server certificate from browser and imported it to client webapp java trust store using keytool. Then it worked.


Now I'm getting this exception.I'm sending redirect URI in the authentication request still showing same error

2019-09-19 06:14:21.843		qtp1606272155-77	SEVERE	Login attempt failed
com.nimbusds.oauth2.sdk.ParseException: Missing redirection URI / HTTP Location header
	at com.nimbusds.openid.connect.sdk.AuthenticationResponseParser.parse(AuthenticationResponseParser.java:128)
	at com.example.server.sso.oidc.Servlets$LoginServlet.authenticate(Servlets.java:168)
	at com.example.server.sso.oidc.Servlets$Servlet.doGet(Servlets.java:69)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:621)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:722)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:769)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:585)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:221)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1125)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:515)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:185)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1059)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.eclipse.jetty.server.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:215)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:97)
	at org.eclipse.jetty.server.Server.handle(Server.java:497)
	at org.eclipse.jetty.server.HttpChannel.handle(HttpChannel.java:311)
	at org.eclipse.jetty.server.HttpConnection.onFillable(HttpConnection.java:248)
	at org.eclipse.jetty.io.AbstractConnection$2.run(AbstractConnection.java:540)
	at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:610)
	at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:539)
	at java.lang.Thread.run(Thread.java:748)

//code
			
AuthenticationRequest authenticationRequest = new AuthenticationRequest.Builder(
  new ResponseType(ResponseType.Value.CODE),
				    scope,
				    clientID,
				    URI.create(redirectUrl))
				    .state(state)
				    .endpointURI(providerMetadata.getAuthorizationEndpointURI())
				    .build();
