### ISSUE TITLE
SpringHibernateJpaPersistenceProvider causes hibernate initialization to fail

### ISSUE THREAD

**Issue by mmoayyed** [mitreid-connect/OpenID-Connect-Java-Spring-Server#882]
I am using a combination of `SpringHibernateJpaPersistenceProvider` and `HibernateJpaVendorAdapter` rather than Eclipse Link. Snippet follows:

``` xml
<bean id="entityManagerFactory" class="org.springframework.orm.jpa.LocalContainerEntityManagerFactoryBean">
        <property name="packagesToScan" value="org.mitre" />
        <property name="persistenceUnitName" value="oidcstorageservice" />
        <property name="persistenceProviderClass" value="org.springframework.orm.jpa.vendor.SpringHibernateJpaPersistenceProvider" />
        <property name="dataSource" ref="dataSource" />
        <property name="jpaVendorAdapter" ref="jpaAdapter" />
    </bean>

<bean id="jpaAdapter" class="org.springframework.orm.jpa.vendor.HibernateJpaVendorAdapter">
        <property name="databasePlatform" value="org.hibernate.dialect.HSQLDialect" />

        <property name="showSql" value="true" />
    </bean>
```

What I see next is:

``` bash
[STDOUT] Caused by: org.hibernate.AnnotationException: Collection has neither generic type or OneToMany.targetEntity() defined: org.mitre.oauth2.model.AuthenticationHolderEntity.authorities
[STDOUT]        at org.hibernate.cfg.annotations.CollectionBinder.getCollectionType(CollectionBinder.java:703) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.annotations.CollectionBinder.bind(CollectionBinder.java:503) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.AnnotationBinder.processElementAnnotations(AnnotationBinder.java:2156) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.AnnotationBinder.processIdPropertiesIfNotAlready(AnnotationBinder.java:963) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.AnnotationBinder.bindClass(AnnotationBinder.java:796) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration$MetadataSourceQueue.processAnnotatedClassesQueue(Configuration.java:3788) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration$MetadataSourceQueue.processMetadata(Configuration.java:3742) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1410) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1844) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) ~[hibernate-entitymanager-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        ... 49 common frames omitted
```

This is with 1.2.

**Comment by selvarajkumarasamy** [comment]
Yes.. Hibernate will look for static property not dynamic..this will cause the problem "private Collection<? extends GrantedAuthority> authorities".

**Comment by selvarajkumarasamy** [comment]
By overriding this property you can solve the issue.

**Comment by mmoayyed** [comment]
Thanks for the update. I am not sure yet whether I actually want to extend that API. Looking around, it seems like a simple fix would be to annotate the getter of that field to note the relationship. I suspect because of type erasure, the generic type gets written away with and Hibernate then gets confused to find the right type. 

A quick search led me to:
http://www.mkyong.com/hibernate/org-hibernate-annotationexception-collection-has-neither-generic-type-or-onetomany-targetentity/

Happy to submit a PR if that is acceptable as a solution though I have not tested it yet.

**Comment by selvarajkumarasamy** [comment]
Yes i agree your point,just simple change required to solve the issue.

**Comment by mmoayyed** [comment]
Same issue with `SavedUserAuthentication`

Once I added the annotations for those two which seems to have solved the problem, I now see this:

```bash
[STDOUT] Caused by: java.lang.IllegalStateException: @Convert placed on Map attribute [org.mitre.oauth2.model.AuthenticationHolderEntity.extensions] must define attributeName of 'key' or 'value'
[STDOUT]        at org.hibernate.cfg.CollectionPropertyHolder.applyLocalConvert(CollectionPropertyHolder.java:142) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.CollectionPropertyHolder.buildAttributeConversionInfoMaps(CollectionPropertyHolder.java:99) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.CollectionPropertyHolder.prepare(CollectionPropertyHolder.java:329) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.annotations.CollectionBinder.bindManyToManySecondPass(CollectionBinder.java:1374) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.annotations.CollectionBinder.bindStarToManySecondPass(CollectionBinder.java:793) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.annotations.MapBinder$1.secondPass(MapBinder.java:107) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.CollectionSecondPass.doSecondPass(CollectionSecondPass.java:70) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration.originalSecondPassCompile(Configuration.java:1695) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration.secondPassCompile(Configuration.java:1424) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.cfg.Configuration.buildSessionFactory(Configuration.java:1844) ~[hibernate-core-4.3.5.Final.jar:4.3.5.Final]
[STDOUT]        at org.hibernate.jpa.boot.internal.EntityManagerFactoryBuilderImpl$4.perform(EntityManagerFactoryBuilderImpl.java:850) ~[hibernate-entitymanager-4.3.5.Final.jar:4.3.5.Final]
```

**Comment by selvarajkumarasamy** [comment]
You should add HashSet.. this will solve the issue.

**Comment by selvarajkumarasamy** [comment]
just comment out the converter.

**Comment by jricher** [comment]
Looks like Hibernate needs more explicit direction than EclipseLink does. As long as the added annotations don't break ElicpseLink (they shouldn't), we'd be happy to incorporate the pull request.
