### ISSUE TITLE
Multiple redirect-uris should disallow pairwise identifiers with no sector identifier

### ISSUE THREAD

**Issue by oharsta** [mitreid-connect/OpenID-Connect-Java-Spring-Server#969]
When a client has multiple redirect URIs, no configured sectorIdentifierUri and the subject type is PAIRWISE then the UUIDPairwiseIdentiferService#getIdentifier fails with a java.lang.IllegalArgumentException caused by the com.google.common.collect.Iterators#getOnlyElement. 

```bash
Caused by: java.lang.IllegalArgumentException: expected one element but was: <http://authz-playground-local:8089/redirect, https://authz-playground.surfconext.nl/redirect, https://authz-playground.test.surfconext.nl/redirect, http://localhost:8889/callback, https://authz-playground.acc.surfconext.nl/redirect>
	at com.google.common.collect.Iterators.getOnlyElement(Iterators.java:317)
	at com.google.common.collect.Iterables.getOnlyElement(Iterables.java:289)
	at org.mitre.openid.connect.service.impl.UUIDPairwiseIdentiferService.getIdentifier(UUIDPairwiseIdentiferService.java:65)
	at org.mitre.openid.connect.service.impl.DefaultUserInfoService.getByUsernameAndClientId(DefaultUserInfoService.java:64)
	at org.mitre.openid.connect.token.ConnectTokenEnhancer.enhance(ConnectTokenEnhancer.java:122)
```

**Comment by jricher** [comment]
Thanks for catching this, shouldn't be a hard fix. Could you please write and submit a unit test that catches this corner case?

**Comment by oharsta** [comment]
I'll do a pull request tomorrow including unit test.

**Comment by jricher** [comment]
Fantastic, thank you!

**Comment by oharsta** [comment]
https://github.com/mitreid-connect/OpenID-Connect-Java-Spring-Server/pull/970

**Comment by jricher** [comment]
Thanks for the pull request, I'm changing the title of this to reflect that the UI should warn the user instead of waiting for the service to pick up on it.
